name: darty_x
description: "A collection of useful extension functions for Dart language to enhance productivity and code readability."
version: 0.0.2
repository: https://github.com/tuanemdev/DartExtension

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
